name: final_project_superbootcamp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.3
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.2.1+2
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  image_picker: ^1.0.7
  http: ^1.2.2
  equatable: ^2.0.5
  lottie: ^3.1.2
  cloud_firestore: ^5.2.1
  provider: ^6.1.2
  pdf: ^3.11.1
  printing: ^5.13.1
  pdfx: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/json/



