name: mini_project_dua
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter_local_notifications: ^17.2.1+2
  flutter_launcher_icons: ^0.13.1
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  image_path: "assets/icons/icon_logo.png" 
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/animation/
    - assets/icons/
    - assets/images/



